import { useState, useEffect } from 'react';
import { Settings } from '../types';
import { DEFAULT_SETTINGS } from '../constants/settings';
import { API_ENDPOINTS } from '../constants/api';
import { TIMING } from '../constants/timing';

export function useSettings() {
  const [settings, setSettings] = useState<Settings>(DEFAULT_SETTINGS);
  const [isSaving, setIsSaving] = useState(false);
  const [saveStatus, setSaveStatus] = useState('');

  useEffect(() => {
    fetch(API_ENDPOINTS.SETTINGS)
      .then(res => res.json())
      .then(data => {
        setSettings({
          CLAUDE_PILOT_MODEL: data.CLAUDE_PILOT_MODEL || DEFAULT_SETTINGS.CLAUDE_PILOT_MODEL,
          CLAUDE_PILOT_CONTEXT_OBSERVATIONS: data.CLAUDE_PILOT_CONTEXT_OBSERVATIONS || DEFAULT_SETTINGS.CLAUDE_PILOT_CONTEXT_OBSERVATIONS,
          CLAUDE_PILOT_WORKER_PORT: data.CLAUDE_PILOT_WORKER_PORT || DEFAULT_SETTINGS.CLAUDE_PILOT_WORKER_PORT,
          CLAUDE_PILOT_WORKER_HOST: data.CLAUDE_PILOT_WORKER_HOST || DEFAULT_SETTINGS.CLAUDE_PILOT_WORKER_HOST,

          CLAUDE_PILOT_CONTEXT_SHOW_READ_TOKENS: data.CLAUDE_PILOT_CONTEXT_SHOW_READ_TOKENS || DEFAULT_SETTINGS.CLAUDE_PILOT_CONTEXT_SHOW_READ_TOKENS,
          CLAUDE_PILOT_CONTEXT_SHOW_WORK_TOKENS: data.CLAUDE_PILOT_CONTEXT_SHOW_WORK_TOKENS || DEFAULT_SETTINGS.CLAUDE_PILOT_CONTEXT_SHOW_WORK_TOKENS,
          CLAUDE_PILOT_CONTEXT_SHOW_SAVINGS_AMOUNT: data.CLAUDE_PILOT_CONTEXT_SHOW_SAVINGS_AMOUNT || DEFAULT_SETTINGS.CLAUDE_PILOT_CONTEXT_SHOW_SAVINGS_AMOUNT,
          CLAUDE_PILOT_CONTEXT_SHOW_SAVINGS_PERCENT: data.CLAUDE_PILOT_CONTEXT_SHOW_SAVINGS_PERCENT || DEFAULT_SETTINGS.CLAUDE_PILOT_CONTEXT_SHOW_SAVINGS_PERCENT,

          CLAUDE_PILOT_CONTEXT_OBSERVATION_TYPES: data.CLAUDE_PILOT_CONTEXT_OBSERVATION_TYPES || DEFAULT_SETTINGS.CLAUDE_PILOT_CONTEXT_OBSERVATION_TYPES,
          CLAUDE_PILOT_CONTEXT_OBSERVATION_CONCEPTS: data.CLAUDE_PILOT_CONTEXT_OBSERVATION_CONCEPTS || DEFAULT_SETTINGS.CLAUDE_PILOT_CONTEXT_OBSERVATION_CONCEPTS,

          CLAUDE_PILOT_CONTEXT_FULL_COUNT: data.CLAUDE_PILOT_CONTEXT_FULL_COUNT || DEFAULT_SETTINGS.CLAUDE_PILOT_CONTEXT_FULL_COUNT,
          CLAUDE_PILOT_CONTEXT_FULL_FIELD: data.CLAUDE_PILOT_CONTEXT_FULL_FIELD || DEFAULT_SETTINGS.CLAUDE_PILOT_CONTEXT_FULL_FIELD,
          CLAUDE_PILOT_CONTEXT_SESSION_COUNT: data.CLAUDE_PILOT_CONTEXT_SESSION_COUNT || DEFAULT_SETTINGS.CLAUDE_PILOT_CONTEXT_SESSION_COUNT,

          CLAUDE_PILOT_CONTEXT_SHOW_LAST_SUMMARY: data.CLAUDE_PILOT_CONTEXT_SHOW_LAST_SUMMARY || DEFAULT_SETTINGS.CLAUDE_PILOT_CONTEXT_SHOW_LAST_SUMMARY,
          CLAUDE_PILOT_CONTEXT_SHOW_LAST_MESSAGE: data.CLAUDE_PILOT_CONTEXT_SHOW_LAST_MESSAGE || DEFAULT_SETTINGS.CLAUDE_PILOT_CONTEXT_SHOW_LAST_MESSAGE,

          CLAUDE_PILOT_SKIP_TOOLS: data.CLAUDE_PILOT_SKIP_TOOLS || DEFAULT_SETTINGS.CLAUDE_PILOT_SKIP_TOOLS,
          CLAUDE_PILOT_LOG_LEVEL: data.CLAUDE_PILOT_LOG_LEVEL || DEFAULT_SETTINGS.CLAUDE_PILOT_LOG_LEVEL,
          CLAUDE_PILOT_MODE: data.CLAUDE_PILOT_MODE || DEFAULT_SETTINGS.CLAUDE_PILOT_MODE,
          CLAUDE_PILOT_FOLDER_MD_EXCLUDE: data.CLAUDE_PILOT_FOLDER_MD_EXCLUDE || DEFAULT_SETTINGS.CLAUDE_PILOT_FOLDER_MD_EXCLUDE,
        });
      })
      .catch(error => {
        console.error('Failed to load settings:', error);
      });
  }, []);

  const saveSettings = async (newSettings: Settings) => {
    setIsSaving(true);
    setSaveStatus('Saving...');

    const response = await fetch(API_ENDPOINTS.SETTINGS, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(newSettings)
    });

    const result = await response.json();

    if (result.success) {
      setSettings(newSettings);
      setSaveStatus('✓ Saved');
      setTimeout(() => setSaveStatus(''), TIMING.SAVE_STATUS_DISPLAY_DURATION_MS);
    } else {
      setSaveStatus(`✗ Error: ${result.error}`);
    }

    setIsSaving(false);
  };

  return { settings, saveSettings, isSaving, saveStatus };
}
