/**
 * Default settings values for Claude Memory
 * Shared across UI components and hooks
 */
export const DEFAULT_SETTINGS = {
  CLAUDE_PILOT_MODEL: 'claude-sonnet-4-5',
  CLAUDE_PILOT_CONTEXT_OBSERVATIONS: '50',
  CLAUDE_PILOT_WORKER_PORT: '41777',
  CLAUDE_PILOT_WORKER_HOST: '127.0.0.1',
  CLAUDE_PILOT_WORKER_BIND: '127.0.0.1',

  CLAUDE_PILOT_CONTEXT_SHOW_READ_TOKENS: 'true',
  CLAUDE_PILOT_CONTEXT_SHOW_WORK_TOKENS: 'true',
  CLAUDE_PILOT_CONTEXT_SHOW_SAVINGS_AMOUNT: 'true',
  CLAUDE_PILOT_CONTEXT_SHOW_SAVINGS_PERCENT: 'true',

  CLAUDE_PILOT_CONTEXT_OBSERVATION_TYPES: 'bugfix,feature,refactor,discovery,decision,change',
  CLAUDE_PILOT_CONTEXT_OBSERVATION_CONCEPTS: 'how-it-works,why-it-exists,what-changed,problem-solution,gotcha,pattern,trade-off',

  CLAUDE_PILOT_CONTEXT_FULL_COUNT: '5',
  CLAUDE_PILOT_CONTEXT_FULL_FIELD: 'narrative',
  CLAUDE_PILOT_CONTEXT_SESSION_COUNT: '10',

  CLAUDE_PILOT_CONTEXT_SHOW_LAST_SUMMARY: 'true',
  CLAUDE_PILOT_CONTEXT_SHOW_LAST_MESSAGE: 'false',

  CLAUDE_PILOT_SKIP_TOOLS: 'ListMcpResourcesTool,SlashCommand,Skill,TodoWrite,AskUserQuestion',
  CLAUDE_PILOT_LOG_LEVEL: 'INFO',
  CLAUDE_PILOT_MODE: 'code',
  CLAUDE_PILOT_FOLDER_MD_EXCLUDE: '[]',
} as const;
